### ISSUE TITLE
Indoor Map Tutorial Does Not Work

### ISSUE THREAD

**Issue by hugoabernier** [Azure-Samples/am-creator-indoor-data-examples#6]
### This issue is for a: (mark with an `x`)
```
- [x] bug report 
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

1. Download Sample-Contoso Drawing Package.zip to your local hard drive.
2. Follow steps in [the indoor maps tutorial](https://docs.microsoft.com/azure/azure-maps/tutorial-creator-indoor-maps)
3. When submitting the API call using postman, you'll get:
```
{
    "error": {
        "code": "400 BadRequest",
        "message": "Bad request - Data with id:upload not found."
    }
}
```

### Any log messages given by the failure
```
{
    "error": {
        "code": "400 BadRequest",
        "message": "Bad request - Data with id:upload not found."
    }
}
```
### Expected/desired behavior
Should upload as per the tutorial

### OS and Version?
Windows 10

**Comment by achukov** [comment]
same error.
Can't Extract zipped file Sample - Contoso Drawing Package.zip

**Comment by andysiu** [comment]
I suspect it was due to not using HTTP POST. It seems that HTTP GET was used.
The file should be uploaded by calling HTTP POST.

**Comment by hugoabernier** [comment]
How embarassing! You are absolutely correct!

Thanks for helping me!
